const TURN_API='https://ydveditxorbtqufwnzpt.supabase.co/functions/v1/d12-player-turn';
const MEMBER_API='https://ydveditxorbtqufwnzpt.supabase.co/functions/v1/d12-membership';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'₦'+Number(n||0).toLocaleString('en-NG',{maximumFractionDigits:0});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let token=localStorage.getItem('d12turn_token')||'', role=localStorage.getItem('d12turn_role')||'', config=null, data=null, view='dashboard', poller=null, online=navigator.onLine, lastTicketNotif='', alertEnabled=false, audioCtx=null;
const ticketParam=new URLSearchParams(location.search).get('ticket');

function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),3000)}
function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem('d12turn_theme',theme);document.querySelector('meta[name="theme-color"]')?.setAttribute('content',theme==='dark'?'#07120f':'#eef3f1')}
function toggleTheme(){setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark')}
setTheme(localStorage.getItem('d12turn_theme')||'dark');

async function api(url,action,payload={},auth=true){
  const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',...(auth&&token?{'Authorization':'Bearer '+token}:{})},body:JSON.stringify({action,...payload})});
  const j=await r.json().catch(()=>({ok:false,error:'Invalid server response'}));
  if(!r.ok||!j.ok){if(r.status===401&&auth&&!['staff_login','member_login'].includes(action)){clearSession();renderLogin()}throw new Error(j.error||'Request failed')}
  return j;
}
const turn=(a,p={},auth=true)=>api(TURN_API,a,p,auth), member=(a,p={},auth=true)=>api(MEMBER_API,a,p,auth);
function saveSession(j){token=j.token;role=j.role;localStorage.setItem('d12turn_token',token);localStorage.setItem('d12turn_role',role)}
function clearSession(){token='';role='';data=null;localStorage.removeItem('d12turn_token');localStorage.removeItem('d12turn_role');clearInterval(poller);poller=null}
async function logout(){try{await member('logout')}catch{}clearSession();renderLogin()}

function logo(){return '<img class="brand-logo" src="../d12-app-icon.svg" alt="D12">'}
function topbar(){return `<div class="topbar glass"><div class="brand">${logo()}<div><h1>D12 PLAYERS TURN</h1><small>Version ${esc(data?.settings?.app_version||config?.app_version||'1.0')} · Live playing-turn control</small></div></div><div class="top-actions"><div class="sync"><span class="dot ${online?'':'off'}"></span>${online?'LIVE SYNC':'OFFLINE'}</div><button class="icon-btn" onclick="toggleTheme()" title="Theme">◐</button><button class="btn small" onclick="logout()">Logout</button></div></div>`}
function nav(){const allowed=data?.role==='admin'?['dashboard','cashier','rackmaster','settings','audit']:data?.role==='cashier'?['dashboard','cashier']:data?.role==='rackmaster'?['dashboard','rackmaster']:['dashboard'];const labels={dashboard:'⌂ Overview',cashier:'₦ Cashier',rackmaster:'◎ Rackmaster',settings:'⚙ Settings',audit:'≡ Audit'};return `<div class="nav">${allowed.map(x=>`<button class="${view===x?'active':''}" onclick="go('${x}')">${labels[x]}</button>`).join('')}</div>`}
function go(v){view=v;renderApp()}
function shell(content){return `<div class="shell">${topbar()}${nav()}<main class="content">${content}</main></div>`}

async function boot(){
  try{config=await turn('public_config',{},false)}catch(e){config={private_test:true,app_version:'1.0',club_name:'D12 Cue Club'}}
  if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}
  if(ticketParam){renderTicketShell();pollTicket(true);poller=setInterval(()=>pollTicket(false),2200);return}
  if(token){try{await enterApp();return}catch(e){clearSession()}}
  renderLogin();
}

function renderLogin(tab='admin'){
  clearInterval(poller);poller=null;
  const privateNote=config?.private_test?'<div class="notice">Private Test mode is ON. Operational access is currently limited to the existing D12 Admin login.</div>':'';
  const tabs=config?.private_test?`<div class="login-tabs"><button class="active">Admin Test Access</button></div>`:`<div class="login-tabs"><button class="${tab==='admin'?'active':''}" onclick="renderLogin('admin')">Admin</button><button class="${tab==='staff'?'active':''}" onclick="renderLogin('staff')">Staff</button><button class="${tab==='member'?'active':''}" onclick="renderLogin('member')">Member</button></div>`;
  let form='';
  if(tab==='staff'&&!config?.private_test)form=`<form id="loginForm" class="stack"><div class="field"><label>Staff username</label><input name="username" autocomplete="username" required></div><div class="field"><label>Password</label><input name="password" type="password" autocomplete="current-password" required></div><button class="btn primary block">Sign in</button></form>`;
  else if(tab==='member'&&!config?.private_test)form=`<form id="loginForm" class="stack"><div class="field"><label>Member ID</label><input name="member_code" placeholder="D12-2026-123456" required></div><div class="field"><label>Member PIN</label><input name="pin" inputmode="numeric" type="password" required></div><button class="btn purple block">Open My Turn</button></form>`;
  else form=`<form id="loginForm" class="stack"><div class="field"><label>D12 Admin password</label><input name="password" type="password" autocomplete="current-password" autofocus required></div><button class="btn primary block">Enter D12 Players Turn</button></form>`;
  $('#root').innerHTML=`<div class="login-wrap"><section class="login-card glass"><div class="login-hero">${logo()}<h1>D12 PLAYERS TURN</h1><p>Realtime queue, payments, rack control and player alerts.</p></div>${privateNote}<br>${tabs}${form}<p class="muted" style="text-align:center;font-size:12px">D12 Cue Club · Touch interface for phone, tablet and PC</p></section></div>`;
  $('#loginForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{let j;if(tab==='staff'&&!config?.private_test)j=await member('staff_login',{role:'staff',username:f.get('username'),password:f.get('password')},false);else if(tab==='member'&&!config?.private_test)j=await member('member_login',{member_code:f.get('member_code'),pin:f.get('pin')},false);else j=await member('staff_login',{role:'admin',password:f.get('password')},false);saveSession(j);await enterApp()}catch(x){toast(x.message)}})
}

async function enterApp(){data=await turn('bootstrap');role=data.role;localStorage.setItem('d12turn_role',role);view=data.role==='rackmaster'?'rackmaster':data.role==='cashier'?'cashier':'dashboard';renderApp();clearInterval(poller);poller=setInterval(()=>refresh(true),2200)}
async function refresh(silent=true){if(!token)return;try{const next=await turn('bootstrap');data=next;online=true;if(!silent)toast('Live board refreshed');renderApp(true)}catch(e){online=false;if(!silent)toast(e.message);updateSyncOnly()}}
function updateSyncOnly(){const s=$('.sync');if(s)s.innerHTML=`<span class="dot ${online?'':'off'}"></span>${online?'LIVE SYNC':'OFFLINE'}`}

function maps(){const p=Object.fromEntries((data?.players||[]).map(x=>[x.id,x])),t=Object.fromEntries((data?.tables||[]).map(x=>[x.id,x])),s=Object.fromEntries((data?.table_states||[]).map(x=>[x.table_id,x]));return{p,t,s}}
function queues(tableId){return (data?.queue||[]).filter(q=>q.table_id===tableId&&['awaiting_payment','queued','called','active'].includes(q.status)).sort((a,b)=>(a.priority-b.priority)||new Date(a.joined_at)-new Date(b.joined_at))}
function waiting(tableId){return queues(tableId).filter(q=>['awaiting_payment','queued','called'].includes(q.status))}
function currentMatch(tableId){return (data?.matches||[]).find(m=>m.table_id===tableId&&m.status==='in_progress')}
function name(id){return maps().p[id]?.full_name||'Unknown player'}
function state(tableId){return maps().s[tableId]||{operational_status:'open',activity_status:'waiting',avg_match_minutes:12}}
function queueWait(tableId){const st=state(tableId),q=waiting(tableId).filter(x=>x.payment_status!=='pending');return Math.max(0,Math.round(q.length*Number(st.avg_match_minutes||data?.settings?.default_match_minutes||12)))}
function statusPill(st){return `<span class="pill ${esc(st.operational_status)}">${esc(st.operational_status.toUpperCase())}</span>`}
function payBadge(q){return q.payment_status==='pending'?'<span class="pill pending">PAYMENT</span>':q.source==='membership'?'<span class="pill active">MEMBER</span>':'<span class="pill cleared">CLEARED</span>'}

function tableCard(t,detail=false){const st=state(t.id),m=currentMatch(t.id),q=waiting(t.id),holder=st.holder_player_id?name(st.holder_player_id):'No holder yet';return `<section class="card glass table-card"><div class="table-title"><div><div class="eyebrow">${esc(st.activity_status.replaceAll('_',' '))}</div><h2>${esc(t.table_name)}</h2></div>${statusPill(st)}</div><div class="holder"><span class="eyebrow">Table holder</span><strong>${esc(holder)}</strong></div>${m?`<div class="match-box"><div class="eyebrow">Match in progress</div><b>${esc(name(m.holder_player_id))}</b> vs <b>${esc(name(m.challenger_player_id))}</b><br><small class="muted">Started ${new Date(m.started_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small>${detail?`<div style="margin-top:10px"><button class="btn primary block" onclick="openFinishMatch('${m.id}')">Finish Match / Record Result</button></div>`:''}</div>`:`<div class="muted" style="margin:10px 0">${q.length} waiting · est. ${queueWait(t.id)} min</div>`}${detail?rackQueue(t.id):`<div class="row"><span class="pill">${q.length} IN LINE</span><span class="pill">~${queueWait(t.id)} MIN</span></div>`}</section>`}

function dashboard(){const active=(data?.matches||[]).length,totalQ=(data?.queue||[]).filter(q=>['queued','called','awaiting_payment'].includes(q.status)).length,pending=(data?.payments||[]).filter(p=>p.kind==='appeal'&&p.status==='pending').length,open=(data?.table_states||[]).filter(s=>s.operational_status==='open').length;return `<div class="grid cols4 section"><div class="card glass kpi"><span class="eyebrow">Open tables</span><b>${open}</b></div><div class="card glass kpi"><span class="eyebrow">Matches live</span><b>${active}</b></div><div class="card glass kpi"><span class="eyebrow">Players waiting</span><b>${totalQ}</b></div><div class="card glass kpi"><span class="eyebrow">Appeals unpaid</span><b>${pending}</b></div></div><div class="grid cols4">${(data?.tables||[]).map(t=>tableCard(t,false)).join('')}</div>`}

function tableOptions(selected=''){return (data?.tables||[]).map(t=>`<option value="${t.id}" ${t.id===selected?'selected':''}>${esc(t.table_name)} · ${waiting(t.id).length} waiting · ~${queueWait(t.id)} min</option>`).join('')}
function cashier(){const appeals=(data?.payments||[]).filter(p=>p.kind==='appeal'&&p.status==='pending');return `<div class="grid cols2 section"><section class="card glass"><div class="eyebrow">Pay as you play</div><h2>Cashier Check-in</h2><p class="muted">Confirm payment first, then place the player directly into the selected table queue.</p><form id="walkinForm" class="stack"><div class="form-grid"><div class="field"><label>Player full name</label><input name="full_name" required autocomplete="off"></div><div class="field"><label>WhatsApp / phone</label><input name="phone" inputmode="tel"></div><div class="field"><label>Paid amount</label><input name="amount" type="number" min="0" value="3000" required></div><div class="field"><label>Payment ref.</label><input name="reference" placeholder="Cash / POS ref."></div></div><div class="field"><label>Chosen table</label><select name="table_id" required>${tableOptions()}</select></div><button class="btn primary block">✓ Payment Confirmed · Add to Queue</button></form></section><section class="card glass"><div class="eyebrow">Subscription / membership</div><h2>Scan Membership Card</h2><p class="muted">Active members bypass the daily payment and join the chosen table immediately.</p><form id="memberQueueForm" class="stack"><div class="field"><label>Card / QR token</label><div class="row"><input id="cardToken" name="card_token" required autocomplete="off" style="flex:1"><button type="button" class="btn purple" onclick="startScanner()">▥ Scan</button></div></div><div class="field"><label>Chosen table</label><select name="table_id" required>${tableOptions()}</select></div><button class="btn good block">Verify Membership · Add to Queue</button></form></section></div><section class="card glass section"><div class="row split"><div><div class="eyebrow">Cashier gate</div><h2>Appeals Awaiting Payment</h2></div><span class="pill ${appeals.length?'pending':'cleared'}">${appeals.length} PENDING</span></div>${appeals.length?`<div class="queue">${appeals.map(p=>`<div class="queue-item"><div class="queue-num">₦</div><div class="queue-name"><b>${esc(name(p.player_id))}</b><small>${money(p.amount)} · ${esc(maps().t[p.table_id]?.table_name||'Table')}</small></div><div class="queue-actions"><button class="btn good small" onclick="payAppeal('${p.id}')">Confirm Paid</button></div></div>`).join('')}</div>`:'<div class="empty">No unpaid appeals. Rackmaster can only rack an appeal after this cashier step is completed.</div>'}</section><section class="card glass"><h2>Live Queue Board</h2><div class="grid cols4">${(data?.tables||[]).map(t=>tableCard(t,false)).join('')}</div></section>`}

function rackQueue(tableId){const q=waiting(tableId);if(!q.length)return '<div class="empty">No player waiting on this table.</div>';return `<div class="queue">${q.map((x,i)=>`<div class="queue-item"><div class="queue-num">${i+1}</div><div class="queue-name"><b>${esc(name(x.player_id))}</b><small>${esc(x.source.toUpperCase())} · ${new Date(x.joined_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small><div style="margin-top:5px">${payBadge(x)}</div></div><div class="queue-actions">${x.payment_status!=='pending'?`<button class="btn small" onclick="callPlayer('${x.id}')">⌁ Call</button>`:''}<button class="btn small" onclick="movePlayer('${x.id}','${tableId}')">⇄ Move</button><button class="btn small warn" onclick="skipPlayer('${x.id}')">No-show</button></div></div>`).join('')}</div>`}
function rackmaster(){return `<div class="notice section">Rackmaster rule: an unpaid appeal remains locked. The <b>Start Next Match</b> action only selects players whose payment/membership clearance is valid.</div><div class="grid cols2">${(data?.tables||[]).map(t=>{const st=state(t.id),m=currentMatch(t.id),eligible=waiting(t.id).filter(q=>q.payment_status!=='pending').length,need=st.holder_player_id?1:2;return `<section class="card glass table-card"><div class="table-title"><div><div class="eyebrow">${esc(st.activity_status.replaceAll('_',' '))}</div><h2>${esc(t.table_name)}</h2></div>${statusPill(st)}</div><div class="holder"><span class="eyebrow">Table holder</span><strong>${esc(st.holder_player_id?name(st.holder_player_id):'No holder yet')}</strong></div>${m?`<div class="match-box"><div class="eyebrow">Playing now</div><b>${esc(name(m.holder_player_id))}</b> vs <b>${esc(name(m.challenger_player_id))}</b><div style="margin-top:10px"><button class="btn primary block" onclick="openFinishMatch('${m.id}')">Finish Match / Record Result</button></div></div>`:`<button class="btn primary block" ${st.operational_status!=='open'||eligible<need?'disabled':''} onclick="startNext('${t.id}')">▶ Start Next Match ${eligible<need?`(${need-eligible} more cleared player${need-eligible===1?'':'s'} needed)`:''}</button>`}<div class="row" style="margin:10px 0"><button class="btn small ${st.operational_status==='open'?'warn':'good'}" onclick="setTableStatus('${t.id}','${st.operational_status==='open'?'paused':'open'}')">${st.operational_status==='open'?'Ⅱ Pause':'▶ Open'}</button>${data.role==='admin'?`<button class="btn small danger" onclick="setTableStatus('${t.id}','closed')">Close</button><button class="btn small" onclick="resetTable('${t.id}')">Reset</button>`:''}</div>${rackQueue(t.id)}</section>`}).join('')}</div>`}

function settingsView(){const s=data.settings||{},staff=data.staff||[],rmap=Object.fromEntries((data.staff_roles||[]).map(r=>[r.staff_id,r]));return `<div class="grid cols2 section"><section class="card glass"><h2>Turn Rules</h2><form id="settingsForm" class="stack"><label class="row"><input name="private_test" type="checkbox" ${s.private_test?'checked':''}> <b>Private Test mode — Admin only</b></label><div class="field"><label>Appeal fee</label><input name="appeal_fee" type="number" min="0" value="${Number(s.appeal_fee||5000)}"></div><div class="field"><label>No-show grace (minutes)</label><input name="no_show_grace_minutes" type="number" min="1" max="30" value="${Number(s.no_show_grace_minutes||3)}"></div><div class="field"><label>Average rack / match time (minutes)</label><input name="default_match_minutes" type="number" min="3" max="120" value="${Number(s.default_match_minutes||12)}"></div><label class="row"><input name="no_consecutive_appeals" type="checkbox" ${s.no_consecutive_appeals?'checked':''}> <b>Block consecutive appeals</b></label><button class="btn primary">Save Turn Rules</button></form></section><section class="card glass"><h2>Create Turn Staff</h2><p class="muted">Creates a D12 staff login, then assigns the role used by this app.</p><form id="createStaffForm" class="stack"><div class="field"><label>Full name</label><input name="full_name" required></div><div class="field"><label>Username</label><input name="username" required></div><div class="field"><label>Temporary password</label><input name="password" type="password" minlength="6" required></div><div class="field"><label>Turn role</label><select name="turn_role"><option value="cashier">Cashier</option><option value="rackmaster">Rackmaster</option><option value="manager">Manager</option></select></div><button class="btn purple">Create Staff Login</button></form></section></div><section class="card glass"><h2>Existing Staff Roles</h2>${staff.length?`<div class="queue">${staff.map(x=>`<div class="queue-item"><div class="queue-num">♙</div><div class="queue-name"><b>${esc(x.full_name)}</b><small>@${esc(x.username)} · ${x.active?'Active':'Disabled'}</small></div><div class="queue-actions"><select id="role-${x.id}" style="min-height:40px;border-radius:12px;background:transparent;color:var(--text);border:1px solid var(--line)"><option value="cashier" ${rmap[x.id]?.turn_role==='cashier'?'selected':''}>Cashier</option><option value="rackmaster" ${rmap[x.id]?.turn_role==='rackmaster'?'selected':''}>Rackmaster</option><option value="manager" ${rmap[x.id]?.turn_role==='manager'?'selected':''}>Manager</option></select><button class="btn small" onclick="assignStaff('${x.id}')">Save Role</button></div></div>`).join('')}</div>`:'<div class="empty">No D12 staff accounts found.</div>'}</section>`}
function auditView(){const rows=data.audit||[];return `<section class="card glass"><div class="row split"><div><h2>Turn Audit Log</h2><p class="muted">Latest 150 operational actions.</p></div><button class="btn small" onclick="refresh(false)">Refresh</button></div>${rows.length?rows.map(a=>`<div class="audit-row"><b>${esc(a.action.replaceAll('_',' '))}</b> · ${esc(a.actor_name)}<br><small class="muted">${new Date(a.created_at).toLocaleString()} ${a.entity_type?`· ${esc(a.entity_type)}`:''}</small></div>`).join(''):'<div class="empty">No actions logged yet.</div>'}</section>`}

function renderApp(fromPoll=false){if(!data)return;let content=view==='cashier'?cashier():view==='rackmaster'?rackmaster():view==='settings'?settingsView():view==='audit'?auditView():dashboard();const active=document.activeElement,activeId=active?.id,selection=active&&'selectionStart' in active?[active.selectionStart,active.selectionEnd]:null;$('#root').innerHTML=shell(content);bindForms();if(fromPoll&&activeId){const el=document.getElementById(activeId);if(el){el.focus();if(selection&&el.setSelectionRange)el.setSelectionRange(...selection)}}}

function bindForms(){
  $('#walkinForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const j=await turn('add_walkin',Object.fromEntries(f));toast('Player paid and added to queue');showTicket(j.ticket);await refresh(true)}catch(x){toast(x.message)}});
  $('#memberQueueForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const j=await turn('enqueue_member',Object.fromEntries(f));toast(`${j.member.full_name} verified and queued`);showTicket(j.ticket);await refresh(true)}catch(x){toast(x.message)}});
  $('#settingsForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await turn('save_settings',{private_test:f.get('private_test')==='on',no_consecutive_appeals:f.get('no_consecutive_appeals')==='on',appeal_fee:Number(f.get('appeal_fee')),no_show_grace_minutes:Number(f.get('no_show_grace_minutes')),default_match_minutes:Number(f.get('default_match_minutes'))});toast('Turn rules saved');config=await turn('public_config',{},false);await refresh(true)}catch(x){toast(x.message)}});
  $('#createStaffForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),turn_role=f.get('turn_role');try{const j=await member('create_staff',{full_name:f.get('full_name'),username:f.get('username'),password:f.get('password'),permissions:{register_members:false,view_members:true,scan_cards:turn_role==='cashier',renewals:false,payments:turn_role==='cashier'}});await turn('assign_staff_role',{staff_id:j.staff.id,turn_role});toast('Turn staff created');await refresh(true)}catch(x){toast(x.message)}})
}

async function payAppeal(id){const reference=prompt('Payment reference (optional):','Cash')??'';try{await turn('pay_appeal',{payment_id:id,reference});toast('Appeal payment confirmed — rack is unlocked');await refresh(true)}catch(x){toast(x.message)}}
async function startNext(tableId){try{await turn('start_next',{table_id:tableId});toast('Match started — player turn alert sent');await refresh(true)}catch(x){toast(x.message)}}
async function callPlayer(id){try{await turn('call_player',{queue_id:id});toast('Player called and alerted');await refresh(true)}catch(x){toast(x.message)}}
async function skipPlayer(id){openModal(`<div class="modal-head"><div><div class="eyebrow">No-show handling</div><h2>What should happen?</h2></div><button class="icon-btn" onclick="closeModal()">×</button></div><div class="choice-grid"><button class="choice" onclick="confirmSkip('${id}',true)"><b>Requeue at End</b><br><span class="muted">Keep player active but move to the end.</span></button><button class="choice" onclick="confirmSkip('${id}',false)"><b>Skip / Leave</b><br><span class="muted">Remove from the active line.</span></button></div>`)}
async function confirmSkip(id,requeue){closeModal();try{await turn('skip_player',{queue_id:id,requeue});toast(requeue?'Player moved to end of queue':'Player skipped');await refresh(true)}catch(x){toast(x.message)}}
function movePlayer(id,current){openModal(`<div class="modal-head"><div><div class="eyebrow">Change table</div><h2>Move Player</h2></div><button class="icon-btn" onclick="closeModal()">×</button></div><div class="field"><label>Desired table</label><select id="moveTarget">${(data.tables||[]).filter(t=>t.id!==current&&state(t.id).operational_status==='open').map(t=>`<option value="${t.id}">${esc(t.table_name)} · ${waiting(t.id).length} waiting · ~${queueWait(t.id)} min</option>`).join('')}</select></div><br><button class="btn primary block" onclick="confirmMove('${id}')">Move to Selected Table</button>`)}
async function confirmMove(id){const target=$('#moveTarget')?.value;if(!target)return toast('No open target table');try{await turn('move_queue',{queue_id:id,target_table_id:target});closeModal();toast('Player moved to new table queue');await refresh(true)}catch(x){toast(x.message)}}
async function setTableStatus(id,status){if(status==='closed'&&!confirm('Close this table? New players will not be added.'))return;try{await turn('set_table_status',{table_id:id,status});toast(`Table ${status}`);await refresh(true)}catch(x){toast(x.message)}}
async function resetTable(id){if(!confirm('Reset this table? Any active match will be voided and the table holder cleared.'))return;try{await turn('reset_table',{table_id:id});toast('Table reset');await refresh(true)}catch(x){toast(x.message)}}
async function assignStaff(id){const r=$(`#role-${CSS.escape(id)}`)?.value||document.getElementById('role-'+id)?.value;try{await turn('assign_staff_role',{staff_id:id,turn_role:r});toast('Staff role saved');await refresh(true)}catch(x){toast(x.message)}}

function openFinishMatch(matchId){const m=(data.matches||[]).find(x=>x.id===matchId);if(!m)return;const others=(data.tables||[]).filter(t=>t.id!==m.table_id&&state(t.id).operational_status==='open');openModal(`<div class="modal-head"><div><div class="eyebrow">Post-match turn decision</div><h2>Record Result</h2><p class="muted">Winner stays. The loser then chooses Appeal, Remain, Change Table or Leave.</p></div><button class="icon-btn" onclick="closeModal()">×</button></div><form id="finishForm" class="stack"><div class="field"><label>Winner</label><div class="choice-grid"><label class="choice"><input type="radio" name="winner" value="${m.holder_player_id}" required> <b>${esc(name(m.holder_player_id))}</b></label><label class="choice"><input type="radio" name="winner" value="${m.challenger_player_id}" required> <b>${esc(name(m.challenger_player_id))}</b></label></div></div><div class="field"><label>Loser choice</label><div class="choice-grid"><label class="choice"><input type="radio" name="action" value="appeal" required onchange="finishChoiceChanged()"> <b>↻ Appeal</b><br><span class="muted">Immediate rematch after cashier payment.</span></label><label class="choice"><input type="radio" name="action" value="remain" required onchange="finishChoiceChanged()"> <b>⌛ Remain</b><br><span class="muted">Join the end of this same table line.</span></label><label class="choice"><input type="radio" name="action" value="change" required onchange="finishChoiceChanged()"> <b>⇄ Change Table</b><br><span class="muted">Choose another table and join its line.</span></label><label class="choice"><input type="radio" name="action" value="leave" required onchange="finishChoiceChanged()"> <b>↗ Leave</b><br><span class="muted">End this playing session.</span></label></div></div><div id="changeTarget" class="field" style="display:none"><label>Desired table</label><select name="target_table_id">${others.map(t=>`<option value="${t.id}">${esc(t.table_name)} · ${waiting(t.id).length} waiting · ~${queueWait(t.id)} min</option>`).join('')}</select></div><button class="btn primary block">Save Result & Continue Turn System</button></form>`);$('#finishForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),action=f.get('action');try{await turn('finish_match',{match_id:matchId,winner_player_id:f.get('winner'),loser_action:action,target_table_id:action==='change'?f.get('target_table_id'):null});closeModal();toast(action==='appeal'?'Result saved — appeal locked until cashier payment':'Result saved — queue updated');await refresh(true)}catch(x){toast(x.message)}})}
function finishChoiceChanged(){const a=document.querySelector('input[name="action"]:checked')?.value;$('#changeTarget').style.display=a==='change'?'grid':'none';document.querySelectorAll('.choice').forEach(x=>x.classList.toggle('selected',!!x.querySelector('input:checked')))}

function openModal(html){$('#modalCard').innerHTML=html;$('#modal').classList.remove('hidden');$('#modal').setAttribute('aria-hidden','false')}
function closeModal(){stopScanner();$('#modal').classList.add('hidden');$('#modal').setAttribute('aria-hidden','true');$('#modalCard').innerHTML=''}
function showTicket(ticket){const url=`${location.origin}${location.pathname}?ticket=${encodeURIComponent(ticket)}`;openModal(`<div class="modal-head"><div><div class="eyebrow">Player alert ticket</div><h2>Queue Confirmed</h2><p class="muted">Have the player scan this once. Their phone will show queue position and receive turn alerts while the page/PWA is open.</p></div><button class="icon-btn" onclick="closeModal()">×</button></div><div id="qr" class="qrbox"></div><div class="mono">${esc(url)}</div><div class="row" style="margin-top:12px"><button class="btn primary" onclick="copyText('${url.replaceAll("'","\\'")}')">Copy Link</button><button class="btn" onclick="window.open('${url}','_blank')">Open Player View</button></div>`);setTimeout(()=>{const q=$('#qr');if(q&&window.QRCode)new QRCode(q,{text:url,width:180,height:180})},100)}
function copyText(s){navigator.clipboard?.writeText(s).then(()=>toast('Copied')).catch(()=>toast('Copy not available'))}

let scannerStream=null,scannerTimer=null;
async function startScanner(){if(!('mediaDevices'in navigator)||!navigator.mediaDevices.getUserMedia)return toast('Camera scanning is not available on this device. Enter the card token manually.');openModal(`<div class="modal-head"><div><div class="eyebrow">Membership card</div><h2>Scan QR / Barcode</h2></div><button class="icon-btn" onclick="closeModal()">×</button></div><video id="scanVideo" class="scanner-video" autoplay playsinline muted></video><p class="muted">Aim the camera at the D12 membership card code.</p>`);try{scannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});const v=$('#scanVideo');v.srcObject=scannerStream;if('BarcodeDetector'in window){const formats=await BarcodeDetector.getSupportedFormats();const wanted=['qr_code','code_128'].filter(x=>formats.includes(x));const detector=new BarcodeDetector({formats:wanted.length?wanted:formats});scannerTimer=setInterval(async()=>{try{const codes=await detector.detect(v);if(codes[0]?.rawValue){const val=codes[0].rawValue;stopScanner();closeModal();const input=$('#cardToken');if(input){input.value=val;input.focus()}toast('Membership card scanned')}}catch{}},500)}else toast('Live barcode detection is not supported here. Use the manual card token field.')}catch(e){closeModal();toast('Camera permission was not granted')}}
function stopScanner(){clearInterval(scannerTimer);scannerTimer=null;if(scannerStream){scannerStream.getTracks().forEach(t=>t.stop());scannerStream=null}}

function renderTicketShell(){$('#root').innerHTML=`<div class="ticket-shell"><div class="topbar glass"><div class="brand">${logo()}<div><h1>D12 PLAYER TURN</h1><small>Personal queue & alert screen</small></div></div><div class="top-actions"><button class="icon-btn" onclick="toggleTheme()">◐</button></div></div><div id="ticketBody" class="card glass ticket-hero"><div class="empty">Loading your live turn…</div></div></div>`}
async function pollTicket(first=false){try{const d=await turn('ticket_status',{ticket:ticketParam},false);online=true;renderTicket(d);handleTicketNotifications(d,first)}catch(e){online=false;const b=$('#ticketBody');if(b)b.innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function renderTicket(d){const q=d.queue,n=d.notifications?.[0],urgent=['REPORT TO TABLE NOW','PLAYING NOW'].some(x=>q.label.startsWith(x));$('#ticketBody').innerHTML=`<div class="eyebrow">${esc(d.player.member?'D12 MEMBER':'D12 PLAYER')}</div><h2>${esc(d.player.full_name)}</h2><div class="ticket-status">${esc(q.label)}</div><div class="ticket-table">${esc(d.table.table_name)}</div>${q.position?`<div class="position-ring"><div><b>${q.position}</b><span>QUEUE POSITION</span></div></div><p class="muted">Estimated wait: <b>${q.estimated_wait_minutes} min</b></p>`:`<div class="position-ring"><div><b>${urgent?'●':'✓'}</b><span>${urgent?'ACTIVE':'TURN STATUS'}</span></div></div>`}${n?`<div class="alert-banner"><b>${esc(n.message)}</b><br><small class="muted">${new Date(n.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></div>`:''}<div class="stack" style="margin-top:14px"><button class="btn primary block" onclick="enableAlerts()">🔔 Enable Sound, Vibration & Notifications</button><button class="btn block" onclick="pollTicket(false)">↻ Refresh Now</button></div><p class="muted" style="font-size:12px">Keep this screen open or install it to your home screen for the best alert experience.</p>`}
function handleTicketNotifications(d,first){const latest=(d.notifications||[])[0];if(!latest)return;if(first){lastTicketNotif=latest.id;return}if(latest.id!==lastTicketNotif){lastTicketNotif=latest.id;triggerPlayerAlert(latest,d)}}
async function enableAlerts(){alertEnabled=true;if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')await audioCtx.resume();if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission();navigator.vibrate?.([100,60,100]);beep(760,0.12);toast('Player alerts enabled')}
function beep(freq=880,dur=.22){if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.2,audioCtx.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur+.03)}
async function triggerPlayerAlert(n,d){const urgent=['turn','recall'].includes(n.kind);navigator.vibrate?.(urgent?[300,120,300,120,500]:[180,80,180]);if(alertEnabled){beep(urgent?1050:820,urgent?.3:.18);if('Notification'in window&&Notification.permission==='granted'){try{const reg=await navigator.serviceWorker.ready;await reg.showNotification('D12 Players Turn',{body:n.message,tag:'d12-turn-'+n.id,renotify:true,icon:'../d12-app-icon.svg',badge:'../d12-app-icon.svg'})}catch{}}}toast(n.message)}

window.addEventListener('online',()=>{online=true;updateSyncOnly()});window.addEventListener('offline',()=>{online=false;updateSyncOnly()});
boot();