// D12 PLAYERS TURN v1.2 registry, shift and scanner upgrade
const V12_API='https://ydveditxorbtqufwnzpt.supabase.co/functions/v1/d12-turn-v12';
const v12=(a,p={},auth=true)=>api(V12_API,a,p,auth);
const V12_ROLE_API='https://ydveditxorbtqufwnzpt.supabase.co/functions/v1/d12-turn-role-v12';
const v12role=(p={})=>api(V12_ROLE_API,'assign_role',p,true);
let v12Identity=null,html5Scanner=null,scannerTarget='membership';

function mergeV12(base,ext){
  const registry=ext.registry||[];
  if(registry.length&&Array.isArray(base.players)){
    const m=Object.fromEntries(registry.map(p=>[p.id,p]));
    base.players=base.players.map(p=>({...p,...(m[p.id]||{})}));
  }
  return {...base,...ext,registry,staff_v12:ext.staff_v12||[],staff_roles_v12:ext.staff_roles_v12||[],active_shift:ext.active_shift||null,is_on_shift:ext.is_on_shift!==false};
}

enterApp=async function(){
  const base=await turn('bootstrap');
  const ext=await v12('bootstrap').catch(()=>({}));
  data=mergeV12(base,ext);role=data.role;localStorage.setItem('d12turn_role',role);view='overview';renderApp();clearInterval(poller);poller=setInterval(()=>refresh(true),2200);
};
refresh=async function(silent=true){
  if(!token)return;
  try{const [base,ext]=await Promise.all([turn('bootstrap'),v12('bootstrap').catch(()=>({}))]);data=mergeV12(base,ext);role=data.role;renderApp(true);if(!silent)toast('Live board refreshed')}catch(e){if(!silent)toast(e.message)}
};

allowedNav=function(){
  if(role==='admin')return[['overview','⌂','Overview'],['active','●','Active Players'],['registry','♙','Player Registry'],['cashier','₦','Cashier'],['rackmaster','◎','Rackmaster'],['staff','♟','Staff & Shifts'],['settings','⚙','Settings'],['audit','≡','Audit']];
  if(role==='cashier')return[['overview','⌂','Overview'],['cashier','₦','Cashier']];
  if(role==='rackmaster')return[['overview','⌂','Overview'],['rackmaster','◎','Rackmaster']];
  return [];
};
renderApp=function(preserveFocus=false){
  if(!data)return;
  if(preserveFocus&&document.activeElement&&['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;
  charts.forEach(c=>{try{c.destroy()}catch{}});charts=[];
  const body=view==='active'?activePlayersView():view==='registry'?registryView():view==='cashier'?cashierView():view==='rackmaster'?rackmasterView():view==='staff'?staffView():view==='settings'?settingsView():view==='audit'?auditView():overviewView();
  $('#root').innerHTML=shell(body);bindForms();setTimeout(initCharts,0);
};

function shiftBanner(kind){
  const sh=data?.active_shift;
  if(!sh)return `<div class="notice v12-shift-note">No active staff shift is configured. Admin can start a shift from <b>Staff & Shifts</b>.</div>`;
  if(data.is_on_shift===false)return `<div class="notice danger-note"><b>OFF SHIFT</b> · This ${esc(kind)} account is not selected for the current shift. Operational controls are locked.</div>`;
  return `<div class="notice good-note"><b>ON SHIFT</b> · ${esc(sh.shift_name)} · Started ${new Date(sh.started_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</div>`;
}

function activePlayers(){
  const rows=[],seen=new Set(),tmap=maps().t;
  for(const q of (data.queue||[])){
    if(!['awaiting_payment','queued','called','active'].includes(q.status))continue;
    const p=player(q.player_id);if(seen.has(p.id))continue;seen.add(p.id);
    const st=state(q.table_id),m=currentMatch(q.table_id);let status=q.status.replaceAll('_',' ').toUpperCase();
    if(m&&(m.holder_player_id===p.id||m.challenger_player_id===p.id))status='PLAYING NOW';
    else if(st.holder_player_id===p.id)status=st.holder_mode==='break'?'TABLE HOLDER · BREAK':st.holder_mode==='ready'?'TABLE HOLDER · READY':'TABLE HOLDER';
    const w=waiting(q.table_id),pos=w.findIndex(x=>x.player_id===p.id)+1;
    rows.push({p,table_id:q.table_id,table_name:tmap[q.table_id]?.table_name||'Table',status,position:pos||null,source:q.source,payment_status:q.payment_status});
  }
  for(const st of (data.table_states||[])){
    for(const id of [st.holder_player_id,st.break_owner_player_id]){if(!id||seen.has(id))continue;seen.add(id);const p=player(id);rows.push({p,table_id:st.table_id,table_name:tmap[st.table_id]?.table_name||'Table',status:st.holder_mode==='break'?'TABLE HOLDER · BREAK':st.holder_mode==='ready'?'TABLE HOLDER · READY':'TABLE HOLDER',position:null,source:'holder',payment_status:'cleared'})}
  }
  return rows.sort((a,b)=>a.table_name.localeCompare(b.table_name)||(a.position||0)-(b.position||0));
}
function activePlayersView(){
  const rows=activePlayers();
  return `<section class="hero-panel glass compact-hero"><div><div class="eyebrow">ACTIVE PLAYER LIST</div><h2>${rows.length} Players In The Turn System</h2><p>Live identification, queue status and table assignment.</p></div></section>
  <section class="card glass"><div class="active-player-grid">${rows.map(x=>`<article class="active-player-card">${avatar(x.p,'lg')}<div class="grow"><div class="row wrap"><b>${esc(x.p.full_name)}</b><span class="pill ${x.status.includes('PLAYING')?'good':x.status.includes('PAYMENT')?'pending':''}">${esc(x.status)}</span></div><small class="mono-id">${esc(x.p.player_code||'ID pending')}</small><div class="active-meta"><span>🎱 ${esc(x.table_name)}</span>${x.position?`<span>Queue #${x.position}</span>`:''}<span>${esc((x.source||'').toUpperCase())}</span></div></div><button class="icon-action" title="Update photo" onclick="pickPlayerPhoto('${x.p.id}')">📷</button></article>`).join('')||'<div class="empty">No active players.</div>'}</div></section>`;
}

function registryView(){
  if(role!=='admin')return '<div class="empty">Admin only.</div>';
  const list=data.registry||[];
  return `<div class="grid two registry-top"><section class="card glass"><div class="eyebrow">PLAYER REGISTRY</div><h2>Create Player</h2><form id="registryCreateForm" class="stack"><div class="field"><label>PLAYER NAME</label><input name="full_name" required></div><div class="field"><label>WHATSAPP / PHONE</label><input name="phone" inputmode="tel"></div><div class="field"><label>PROFILE PHOTO</label><input name="photo" type="file" accept="image/*" capture="user"></div><button class="btn primary block">Create Player + Generate ID & QR</button></form></section>
  <section class="card glass"><div class="eyebrow">REGISTRY SUMMARY</div><h2>${list.length} Registered Players</h2><div class="field"><label>SEARCH</label><input id="registrySearch" placeholder="Name, ID or phone" oninput="filterRegistry()"></div><div class="registry-kpis"><span><b>${list.filter(x=>x.member_id).length}</b> Members</span><span><b>${list.filter(x=>!x.member_id).length}</b> Walk-ins</span><span><b>${activePlayers().length}</b> Active</span></div></section></div>
  <section class="card glass"><div id="registryList" class="registry-list">${list.map(registryRow).join('')||'<div class="empty">No registered players yet.</div>'}</div></section>`;
}
function registryRow(p){return `<article class="registry-row" data-search="${esc(`${p.full_name} ${p.player_code||''} ${p.phone||''}`.toLowerCase())}">${avatar(p,'md')}<div class="grow"><b>${esc(p.full_name)}</b><small>${esc(p.player_code||'')} · ${esc(p.phone||'No phone')}</small></div><span class="pill">${p.member_id?'MEMBER':'PLAYER'}</span><button class="btn small" onclick="showRegistryQR('${p.id}')">▦ QR</button><button class="btn small" onclick="editRegistryPlayer('${p.id}')">Edit</button></article>`}
function filterRegistry(){const q=String($('#registrySearch')?.value||'').toLowerCase();$$('#registryList .registry-row').forEach(el=>el.style.display=el.dataset.search.includes(q)?'':'none')}
function showRegistryQR(id){const p=(data.registry||[]).find(x=>x.id===id);if(!p)return;const qr=`D12PLAYER:${p.qr_token}`;openModal(`<div class="modal-head"><div><div class="eyebrow">D12 PLAYER ID</div><h2>${esc(p.full_name)}</h2></div><button class="icon-btn" onclick="closeModal()">×</button></div><div class="identity-card">${avatar(p,'xl')}<b>${esc(p.player_code)}</b><small>${esc(p.phone||'')}</small><div id="registryQr" class="qrbox"></div><div class="mono">${esc(qr)}</div><button class="btn primary" onclick="copyText('${esc(p.player_code)}')">Copy Player ID</button></div>`);setTimeout(()=>{const q=$('#registryQr');if(q&&window.QRCode)new QRCode(q,{text:qr,width:210,height:210})},80)}
function editRegistryPlayer(id){const p=(data.registry||[]).find(x=>x.id===id);if(!p)return;openModal(`<div class="modal-head"><h2>Edit Player</h2><button class="icon-btn" onclick="closeModal()">×</button></div><form id="registryEditForm" class="stack"><input type="hidden" name="player_id" value="${p.id}"><div class="field"><label>PLAYER ID</label><input value="${esc(p.player_code)}" disabled></div><div class="field"><label>NAME</label><input name="full_name" value="${esc(p.full_name)}" required></div><div class="field"><label>WHATSAPP / PHONE</label><input name="phone" value="${esc(p.phone||'')}"></div><div class="field"><label>REPLACE PHOTO</label><input name="photo" type="file" accept="image/*" capture="user"></div><button class="btn primary block">Save Player</button></form>`);bindRegistryEdit()}
function bindRegistryEdit(){$('#registryEditForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const file=f.get('photo'),photo=file&&file.size?await compressImage(file):undefined;await v12('update_player',{player_id:f.get('player_id'),full_name:f.get('full_name'),phone:f.get('phone'),...(photo?{photo_data:photo}:{})});closeModal();toast('Player updated');await refresh(true)}catch(x){toast(x.message)}})}

cashierView=function(){
  if(data.active_shift&&data.is_on_shift===false)return shiftBanner('cashier');
  const appeals=(data.payments||[]).filter(p=>p.kind==='appeal'&&p.status==='pending'),registry=data.registry||[];
  return `${role==='cashier'?shiftBanner('cashier'):''}<div class="grid two cashier-grid">
  <section class="card glass"><div class="eyebrow">REGISTERED PLAYER</div><h2>Fast Check-in</h2><form id="registeredQueueForm" class="stack"><div class="field"><label>SEARCH / SELECT PLAYER</label><input id="playerSelectSearch" placeholder="Type name, ID or phone" oninput="filterPlayerSelect()"><select id="registeredPlayer" name="player_id" size="5" onchange="showSelectedPlayer()">${registry.map(p=>`<option value="${p.id}" data-search="${esc(`${p.full_name} ${p.player_code} ${p.phone||''}`.toLowerCase())}">${esc(p.player_code)} · ${esc(p.full_name)} · ${esc(p.phone||'No phone')}</option>`).join('')}</select></div><div id="selectedPlayerPreview" class="selected-player-preview"><span>Select a player from the registry.</span></div><div class="row wrap"><button type="button" class="btn" onclick="startScanner('registry')">▦ Scan Player QR</button><button type="button" class="btn" onclick="go('registry')" ${role==='admin'?'':'disabled'}>Open Registry</button></div><div class="row"><div class="field grow"><label>AMOUNT</label><input name="amount" type="number" min="0" value="3000"></div><div class="field grow"><label>REFERENCE</label><input name="reference" placeholder="Cash / POS"></div></div><div class="field"><label>TABLE</label><select name="table_id">${tableOptions()}</select></div><button class="btn primary block">✓ Pay & Add Selected Player</button></form></section>
  <section class="card glass"><div class="eyebrow">NEW / WALK-IN PLAYER</div><h2>Quick Registration & Check-in</h2><form id="walkinForm" class="stack"><div class="field"><label>PLAYER FULL NAME</label><input name="full_name" required></div><div class="field"><label>WHATSAPP / PHONE</label><input name="phone" inputmode="tel"></div><div class="field"><label>PLAYER PHOTO</label><input name="photo" type="file" accept="image/*" capture="user"></div><div class="row"><div class="field grow"><label>AMOUNT</label><input name="amount" type="number" min="0" value="3000"></div><div class="field grow"><label>REFERENCE</label><input name="reference" placeholder="Cash / POS"></div></div><div class="field"><label>TABLE</label><select name="table_id">${tableOptions()}</select></div><button class="btn primary block">✓ Register, Pay & Add to Queue</button></form></section>
  </div>
  <section class="card glass section"><div class="eyebrow">MEMBERSHIP</div><h2>Scan Membership Card</h2><form id="memberQueueForm" class="scanner-form"><div class="field grow"><label>CARD / QR TOKEN</label><input id="cardToken" name="card_token" required></div><button type="button" class="btn" onclick="startScanner('membership')">▦ Camera Scanner</button><button type="button" class="btn" onclick="pasteScannerValue('membership')">Paste</button><button type="button" class="btn" onclick="scanImageFile('membership')">Image</button><a class="btn small" target="_blank" rel="noopener" href="https://play.google.com/store/search?q=qr%20code%20scanner&c=apps">Google Play</a><a class="btn small" target="_blank" rel="noopener" href="https://apps.apple.com/us/search?term=qr%20code%20scanner">App Store</a><div class="field"><label>TABLE</label><select name="table_id">${tableOptions()}</select></div><button class="btn good">Verify Member & Add</button></form><p class="muted">External scanner apps can scan the code; copy the result, return here and tap <b>Paste</b>.</p></section>
  <section class="card glass section"><div class="row split"><div><div class="eyebrow">APPEAL GATE</div><h2>Appeals Awaiting Cashier</h2></div><span class="pill ${appeals.length?'pending':'good'}">${appeals.length} PENDING</span></div>${appeals.length?appeals.map(p=>`<div class="queue-row">${avatar(player(p.player_id),'sm')}<div class="grow"><b>${esc(player(p.player_id).full_name)}</b><small>${money(p.amount)} · ${esc(maps().t[p.table_id]?.table_name||'Table')}</small></div><button class="btn good" onclick="payAppeal('${p.id}')">Confirm Paid</button></div>`).join(''):'<div class="empty">No unpaid appeals.</div>'}</section>`;
};
function filterPlayerSelect(){const q=String($('#playerSelectSearch')?.value||'').toLowerCase();$$('#registeredPlayer option').forEach(o=>o.hidden=!o.dataset.search.includes(q))}
function showSelectedPlayer(){const p=(data.registry||[]).find(x=>x.id===$('#registeredPlayer')?.value),box=$('#selectedPlayerPreview');if(!box)return;box.innerHTML=p?`${avatar(p,'md')}<div><b>${esc(p.full_name)}</b><small>${esc(p.player_code)} · ${esc(p.phone||'No phone')}</small></div>`:'<span>Select a player from the registry.</span>'}

const v11BindForms=bindForms;
bindForms=function(){
  v11BindForms();
  $('#registeredQueueForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{if(!f.get('player_id'))throw new Error('Select a registered player.');const j=await v12('queue_registered_player',{player_id:f.get('player_id'),table_id:f.get('table_id'),amount:Number(f.get('amount')),reference:f.get('reference')});toast(`${j.player.full_name} paid and queued`);showTicket(j.ticket);await refresh(true)}catch(x){toast(x.message)}});
  $('#registryCreateForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const file=f.get('photo'),photo=file&&file.size?await compressImage(file):'';const j=await v12('create_player',{full_name:f.get('full_name'),phone:f.get('phone'),photo_data:photo});toast(`${j.player.player_code} created`);await refresh(true);showRegistryQR(j.player.id)}catch(x){toast(x.message)}});
  $('#shiftForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const j=await v12('start_shift',{shift_name:f.get('shift_name'),cashier_staff_id:f.get('cashier_staff_id'),rackmaster_1_staff_id:f.get('rackmaster_1_staff_id'),rackmaster_2_staff_id:f.get('rackmaster_2_staff_id'),rackmaster_1_tables:f.getAll('rm1_tables'),rackmaster_2_tables:f.getAll('rm2_tables')});toast(`${j.shift.shift_name} started`);await refresh(true)}catch(x){toast(x.message)}});
  $('#createStaffForm')?.replaceWith($('#createStaffForm')?.cloneNode(true)||document.createElement('div'));
  const sf=$('#createStaffForm');sf?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),r=f.get('turn_role');try{const j=await member('create_staff',{full_name:f.get('full_name'),username:f.get('username'),password:f.get('password'),permissions:{view_members:true,scan_cards:r==='cashier',payments:r==='cashier'}});await v12role({staff_id:j.staff.id,turn_role:r});const file=f.get('photo');if(file&&file.size){const photo=await compressImage(file);await turn('save_staff_photo',{staff_id:j.staff.id,turn_role:r,photo_data:photo})}toast(`${r} account created`);await refresh(true)}catch(x){toast(x.message)}});
};

staffView=function(){
  if(role!=='admin')return '<div class="empty">Admin only.</div>';
  const roles=data.staff_roles_v12||[],staff=data.staff_v12||[],racks=roles.filter(x=>x.turn_role==='rackmaster').map(r=>({...r,staff:staff.find(s=>s.id===r.staff_id)})),cash=roles.filter(x=>x.turn_role==='cashier').map(r=>({...r,staff:staff.find(s=>s.id===r.staff_id)})),sh=data.active_shift;
  const slot=(x,label)=>x?`<div class="staff-slot">${avatar({full_name:x.staff?.full_name,photo_data:x.profile_photo_data},'md')}<div class="grow"><b>${esc(x.staff?.full_name||label)}</b><small>@${esc(x.staff?.username||'')}</small></div><button class="icon-action" onclick="pickStaffPhoto('${x.staff_id}','${x.turn_role}')">📷</button></div>`:`<div class="staff-slot vacant"><div class="avatar md placeholder">+</div><div><b>${label}</b><small>Vacant</small></div></div>`;
  const staffName=id=>staff.find(s=>s.id===id)?.full_name||'Not selected',tableName=id=>(data.cue_tables_v12||[]).find(t=>t.id===id)?.table_name||'Table';
  const shiftTables=sh?.table_assignments||[];
  return `<section class="hero-panel glass compact-hero"><div><div class="eyebrow">STAFF & SHIFT CONTROL</div><h2>4 Rackmasters · 2 Cashiers · 3 Active Per Shift</h2><p>Each shift uses 2 rackmasters covering 2 tables each, plus 1 cashier.</p></div>${sh?`<span class="pill good">${esc(sh.shift_name)} ACTIVE</span>`:'<span class="pill pending">NO ACTIVE SHIFT</span>'}</section>
  <div class="grid two staff-structure"><section class="card glass"><h2>Rackmaster Structure</h2><p class="muted">Four rackmasters are kept on the roster; two are selected per shift.</p><div class="staff-stack">${[0,1,2,3].map(i=>slot(racks[i],`Rackmaster ${i+1}`)).join('')}</div></section><section class="card glass"><h2>Cashier Structure</h2><p class="muted">Two cashiers are kept on the roster; one runs each shift.</p><div class="staff-stack">${[0,1].map(i=>slot(cash[i],`Cashier ${i+1}`)).join('')}</div></section></div>
  <div class="grid two"><section class="card glass"><h2>Create Staff Account</h2><form id="createStaffForm" class="stack"><div class="field"><label>FULL NAME</label><input name="full_name" required></div><div class="field"><label>USERNAME</label><input name="username" required></div><div class="field"><label>PASSWORD</label><input name="password" type="password" minlength="6" required></div><div class="field"><label>ROLE</label><select name="turn_role"><option value="rackmaster">Rackmaster</option><option value="cashier">Cashier</option></select></div><div class="field"><label>PROFILE PHOTO</label><input name="photo" type="file" accept="image/*" capture="user"></div><button class="btn primary">Create Staff</button></form></section>
  <section class="card glass"><h2>Active Shift</h2>${sh?`<div class="shift-live"><span class="live-dot"></span><div><b>${esc(sh.shift_name)}</b><small>Started ${new Date(sh.started_at).toLocaleString()}</small></div></div><div class="shift-person"><b>Cashier</b><span>${esc(staffName(sh.cashier_staff_id))}</span></div><div class="shift-person"><b>Rackmaster 1</b><span>${esc(staffName(sh.rackmaster_1_staff_id))} · ${shiftTables.filter(x=>x.rackmaster_staff_id===sh.rackmaster_1_staff_id).map(x=>tableName(x.table_id)).join(', ')}</span></div><div class="shift-person"><b>Rackmaster 2</b><span>${esc(staffName(sh.rackmaster_2_staff_id))} · ${shiftTables.filter(x=>x.rackmaster_staff_id===sh.rackmaster_2_staff_id).map(x=>tableName(x.table_id)).join(', ')}</span></div><button class="btn danger block" onclick="endShift()">End Current Shift</button>`:'<div class="empty">No staff shift is currently active.</div>'}</section></div>
  <section class="card glass section"><h2>Start / Change Shift</h2><form id="shiftForm" class="stack"><div class="form-grid"><div class="field"><label>SHIFT NAME</label><input name="shift_name" placeholder="Morning Shift / Evening Shift" required></div><div class="field"><label>CASHIER ON SHIFT</label><select name="cashier_staff_id" required><option value="">Select cashier</option>${cash.map(x=>`<option value="${x.staff_id}">${esc(x.staff?.full_name||'Cashier')}</option>`).join('')}</select></div><div class="field"><label>RACKMASTER 1</label><select name="rackmaster_1_staff_id" required><option value="">Select rackmaster</option>${racks.map(x=>`<option value="${x.staff_id}">${esc(x.staff?.full_name||'Rackmaster')}</option>`).join('')}</select></div><div class="field"><label>RACKMASTER 2</label><select name="rackmaster_2_staff_id" required><option value="">Select rackmaster</option>${racks.map(x=>`<option value="${x.staff_id}">${esc(x.staff?.full_name||'Rackmaster')}</option>`).join('')}</select></div></div><div class="grid two"><div class="field"><label>RACKMASTER 1 · SELECT 2 TABLES</label><div class="check-grid">${(data.cue_tables_v12||[]).map(t=>`<label><input type="checkbox" name="rm1_tables" value="${t.id}"> ${esc(t.table_name)}</label>`).join('')}</div></div><div class="field"><label>RACKMASTER 2 · SELECT 2 TABLES</label><div class="check-grid">${(data.cue_tables_v12||[]).map(t=>`<label><input type="checkbox" name="rm2_tables" value="${t.id}"> ${esc(t.table_name)}</label>`).join('')}</div></div></div><button class="btn primary block">Activate Shift</button></form></section>`;
};
async function endShift(){if(!confirm('End the active shift?'))return;try{await v12('end_shift');toast('Shift ended');await refresh(true)}catch(x){toast(x.message)}}

const v11RackmasterView=rackmasterView;
rackmasterView=function(){if(data.active_shift&&data.is_on_shift===false)return shiftBanner('rackmaster');return `${role==='rackmaster'?shiftBanner('rackmaster'):''}${v11RackmasterView()}`};

openFinishMatch=function(matchId){
  const m=(data.matches||[]).find(x=>x.id===matchId);if(!m)return;const a=player(m.holder_player_id),b=player(m.challenger_player_id),others=(data.all_table_summaries||[]).filter(t=>t.id!==m.table_id&&t.operational_status==='open');
  const act=(value,icon,title,desc)=>`<label class="decision-card"><input type="radio" name="action" value="${value}" required onchange="finishChoice()"><span class="decision-icon">${icon}</span><b>${title}</b><small>${desc}</small></label>`;
  openModal(`<div class="modal-head"><div><div class="eyebrow">RECORD RESULT</div><h2>Winner & Loser Decision</h2></div><button class="icon-btn" onclick="closeModal()">×</button></div><form id="finishForm" class="stack"><div class="field"><label>WINNER</label><div class="winner-grid glossy-winners"><label>${avatar(a,'lg')}<input type="radio" name="winner" value="${a.id}" required><b>${esc(a.full_name)}</b></label><label>${avatar(b,'lg')}<input type="radio" name="winner" value="${b.id}" required><b>${esc(b.full_name)}</b></label></div></div><div class="field"><label>LOSER CHOICE</label><div class="action-grid glossy-actions">${act('appeal','↻','Appeal','Immediate rematch after cashier clears payment.')}${act('remain','⌛','Remain','Join the end of this table queue.')}${act('change','⇄','Change Table','Choose another table and join its line.')}${act('leave','↗','Leave','End this playing session.')}</div></div><div id="changeTarget" class="field hidden"><label>NEW TABLE</label><select name="target_table_id">${others.map(t=>`<option value="${t.id}">${esc(t.table_name)} · ${t.queue_count} in line · ~${t.estimated_wait_minutes} min</option>`).join('')}</select></div><button class="btn primary block">Save Result</button></form>`);
  $('#finishForm').addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget),actn=f.get('action');try{await turn('finish_match',{match_id:matchId,winner_player_id:f.get('winner'),loser_action:actn,target_table_id:actn==='change'?f.get('target_table_id'):null});closeModal();toast(actn==='appeal'?'Appeal created — cashier must clear payment':'Result saved');await refresh(true)}catch(x){toast(x.message)}})
};

function scannerValue(raw){let v=String(raw||'').trim();try{const u=new URL(v);return u.searchParams.get('card_token')||u.searchParams.get('token')||v}catch{return v}}
startScanner=async function(target='membership'){
  scannerTarget=target;
  openModal(`<div class="modal-head"><div><div class="eyebrow">QR SCANNER</div><h2>${target==='registry'?'Scan Registered Player':'Scan Membership Card'}</h2></div><button class="icon-btn" onclick="closeModal()">×</button></div><div id="qr-reader" class="qr-reader"></div><div class="scanner-fallback"><button class="btn" onclick="scanImageFile('${target}')">Choose QR Image</button><button class="btn" onclick="pasteScannerValue('${target}')">Paste Scanned Value</button></div><p class="muted">If camera access is blocked, use an external QR scanner app, copy the result, then return and tap Paste.</p><div class="row wrap"><a class="btn small" target="_blank" rel="noopener" href="https://play.google.com/store/search?q=qr%20code%20scanner&c=apps">Google Play QR scanners</a><a class="btn small" target="_blank" rel="noopener" href="https://apps.apple.com/us/search?term=qr%20code%20scanner">App Store QR scanners</a></div>`);
  if(!window.Html5Qrcode){toast('Camera library is still loading. Use Image or Paste.');return}
  try{html5Scanner=new Html5Qrcode('qr-reader');await html5Scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:240,height:240}},raw=>handleScannedValue(raw,target),()=>{})}catch(e){toast('Camera could not start. Use Image, Paste or an external scanner app.')}
};
async function handleScannedValue(raw,target){try{await stopScanner();closeModal();if(target==='membership'){const el=$('#cardToken');if(el){el.value=scannerValue(raw);el.focus()}toast('Membership QR scanned')}else{const j=await v12('player_qr_lookup',{qr_value:raw});const sel=$('#registeredPlayer');if(sel){sel.value=j.player.id;showSelectedPlayer()}toast(`${j.player.full_name} selected`)}}catch(x){toast(x.message)}}
stopScanner=async function(){clearInterval(scannerTimer);scannerTimer=null;if(scannerStream){scannerStream.getTracks().forEach(t=>t.stop());scannerStream=null}if(html5Scanner){try{await html5Scanner.stop()}catch{}try{await html5Scanner.clear()}catch{}html5Scanner=null}}
async function scanImageFile(target='membership'){const i=document.createElement('input');i.type='file';i.accept='image/*';i.onchange=async()=>{if(!i.files?.[0])return;if(!window.Html5Qrcode)return toast('QR image reader is unavailable.');try{const temp=document.createElement('div');temp.id='qr-file-temp';temp.style.display='none';document.body.appendChild(temp);const qr=new Html5Qrcode('qr-file-temp');const raw=await qr.scanFile(i.files[0],true);await qr.clear();temp.remove();await handleScannedValue(raw,target)}catch{toast('No readable QR code was found in that image.')}};i.click()}
async function pasteScannerValue(target='membership'){try{const raw=await navigator.clipboard.readText();if(!raw)throw new Error();await handleScannedValue(raw,target)}catch{toast('Clipboard access is unavailable. Paste the code manually into the field.')}}

const v11RenderLogin=renderLogin;
renderLogin=function(tab='admin',playerMode='identity'){
  if(tab!=='player')return v11RenderLogin(tab);
  clearInterval(poller);
  $('#root').innerHTML=`<div class="login-wrap"><section class="login-card glass"><div class="login-logo-wrap">${logo('login-logo')}</div><h1>D12 PLAYER LOGIN</h1><p>View your preferred playing table and live queue position.</p><div class="login-tabs"><button onclick="renderLogin('admin')">Admin</button><button onclick="renderLogin('cashier')">Cashier</button><button onclick="renderLogin('rackmaster')">Rackmaster</button><button class="active">Player</button></div><div class="player-login-mode"><button class="${playerMode==='identity'?'active':''}" onclick="renderLogin('player','identity')">Player ID + WhatsApp</button><button class="${playerMode==='ticket'?'active':''}" onclick="renderLogin('player','ticket')">Ticket / QR Code</button></div>${playerMode==='identity'?`<form id="identityLoginForm" class="stack"><div class="field"><label>PLAYER ID</label><input name="player_code" placeholder="D12P-100001" required></div><div class="field"><label>WHATSAPP / PHONE NUMBER</label><input name="phone" inputmode="tel" required></div><button class="btn primary block">Open My Dashboard</button></form>`:`<form id="ticketLoginForm" class="stack"><div class="field"><label>PLAYER TICKET CODE / LINK</label><input name="ticket" required></div><button class="btn primary block">Open My Playing Turn</button></form>`}<div class="device-picker"><span>Display</span>${[['auto','Auto'],['mobile','Mobile'],['tablet','Tablet'],['pc','PC']].map(([v,l])=>`<button class="${deviceMode===v?'active':''}" onclick="applyDevice('${v}');renderLogin('player','${playerMode}')">${l}</button>`).join('')}</div><div class="login-theme"><span>Theme</span>${themeSelect()}</div></section></div>`;
  $('#identityLoginForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const j=await v12('player_identity_login',{player_code:f.get('player_code'),phone:f.get('phone')},false);v12Identity=j;if(j.ticket){ticketParam=j.ticket;localStorage.setItem('d12turn_player_ticket',ticketParam);renderPlayerShell();pollPlayer(true);poller=setInterval(()=>pollPlayer(false),2200)}else renderIdentityDashboard(j)}catch(x){toast(x.message)}});
  $('#ticketLoginForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);let raw=String(f.get('ticket')||'').trim();try{const u=new URL(raw);raw=u.searchParams.get('ticket')||raw}catch{};try{const j=await turn('player_login',{ticket:raw},false);ticketParam=j.ticket;localStorage.setItem('d12turn_player_ticket',ticketParam);renderPlayerShell();pollPlayer(true);poller=setInterval(()=>pollPlayer(false),2200)}catch(x){toast(x.message)}});
};
function renderIdentityDashboard(j){const p=j.player;$('#root').innerHTML=`<div class="player-shell"><header class="topbar glass"><div class="brand">${logo('top-logo')}<div><h1>D12 PLAYER DASHBOARD</h1><small>${esc(p.player_code)}</small></div></div><div>${themeSelect()}</div></header><main class="content"><section class="card glass player-main">${avatar(p,'xl')}<div><div class="eyebrow">REGISTERED PLAYER</div><h2>${esc(p.full_name)}</h2><p class="muted">No active playing turn is currently linked to your account.</p></div></section><section class="card glass"><h3>Table Summary</h3><div class="grid table-summaries">${(j.table_summaries||[]).map(x=>`<div class="summary-card"><div class="summary-ring">${x.queue_count}</div><div><b>${esc(x.table_name)}</b><p>${x.queue_count} in line · ${x.estimated_wait_minutes} min wait</p></div></div>`).join('')}</div></section><button class="btn block" onclick="renderLogin('player','identity')">Sign Out</button></main></div>`}

settingsView=function(){if(role!=='admin')return '<div class="empty">Admin only.</div>';const s=data.settings||{};return `<section class="card glass"><h2>Turn Rules · Version 1.2</h2><form id="settingsForm" class="stack"><div class="form-grid"><div class="field"><label>APPEAL FEE</label><input name="appeal_fee" type="number" value="${Number(s.appeal_fee||0)}"></div><div class="field"><label>NO-SHOW GRACE (MIN)</label><input name="no_show_grace_minutes" type="number" value="${Number(s.no_show_grace_minutes||5)}"></div><div class="field"><label>DEFAULT MATCH TIME (MIN)</label><input name="default_match_minutes" type="number" value="${Number(s.default_match_minutes||12)}"></div></div><label class="check"><input name="no_consecutive_appeals" type="checkbox" ${s.no_consecutive_appeals?'checked':''}> Block consecutive appeals</label><button class="btn primary">Save Version 1.2 Settings</button></form></section>`};
