// D12 PLAYERS TURN v1.6.1 — approvals, arena exit, player transfers, membership ID and theme fixes
const V161_API='https://ydveditxorbtqufwnzpt.supabase.co/functions/v1/d12-turn-v161';
const v161=(a,p={},auth=true)=>api(V161_API,a,p,auth);

function mergeV161(base,ext){
  return {...base,
    checkin_requests:ext?.checkin_requests||[],
    player_transfer_requests:ext?.transfer_requests||[],
    reset_requests:ext?.reset_requests||[]
  };
}
function v161Signature(d){
  return v13Signature(d)+JSON.stringify({
    ci:(d.checkin_requests||[]).map(x=>[x.id,x.status,x.table_id,x.player_id,x.resolved_at]),
    tr:(d.player_transfer_requests||[]).map(x=>[x.id,x.status,x.source_approval,x.target_approval,x.from_table_id,x.to_table_id,x.updated_at]),
    rr:(d.reset_requests||[]).map(x=>[x.id,x.status,x.table_id,x.resolved_at])
  });
}
enterApp=async function(){
  const [base,ext12,ext13,ext14,ext161]=await Promise.all([
    turn('bootstrap'),v12('bootstrap').catch(()=>({})),v13('bootstrap').catch(()=>({})),v14('bootstrap').catch(()=>({})),v161('bootstrap').catch(()=>({}))
  ]);
  data=mergeV161(mergeV14(mergeV13(mergeV12(base,ext12),ext13),ext14),ext161);
  role=data.role;localStorage.setItem('d12turn_role',role);view='overview';
  v13LastSignature=v161Signature(data);v13AnimateOverview=true;renderApp();clearInterval(poller);poller=setInterval(()=>refresh(true),2200);
};
refresh=async function(silent=true){
  if(!token)return;
  try{
    const [base,ext12,ext13,ext14,ext161]=await Promise.all([
      turn('bootstrap'),v12('bootstrap').catch(()=>({})),v13('bootstrap').catch(()=>({})),v14('bootstrap').catch(()=>({})),v161('bootstrap').catch(()=>({}))
    ]);
    const next=mergeV161(mergeV14(mergeV13(mergeV12(base,ext12),ext13),ext14),ext161),sig=v161Signature(next),changed=sig!==v13LastSignature;
    data=next;role=next.role;
    if(changed){v13LastSignature=sig;v13AnimateOverview=view==='overview';renderApp(true)}
    if(!silent)toast(changed?'Live board updated':'Live board is already current');
  }catch(e){if(!silent)toast(e.message)}
};

themeSelect=function(){
  const opts=[['dark','Dark Glass'],['darkgray','Dark Grey'],['light','Plain White'],['snooker','Snooker Green'],['gold','9-Ball Gold'],['blue','Midnight Blue']];
  return `<select class="mini-select" onchange="applyTheme(this.value)">${opts.map(([v,l])=>`<option value="${v}" ${theme===v?'selected':''}>${l}</option>`).join('')}</select>`;
};

payBadge=function(q){
  if(q.payment_status==='pending')return '<span class="pill pending">PAYMENT</span>';
  if(q.source==='membership')return '<span class="pill good">MEMBER</span>';
  if(q.source==='appeal')return '<span class="pill warn">APPEAL</span>';
  if(q.clearance_label)return `<span class="pill cleared clearance-label">${esc(q.clearance_label)}</span>`;
  return '<span class="pill cleared">CLEARED</span>';
};

function goToTable(tableId){
  view='rackmaster';renderApp();
  requestAnimationFrame(()=>{
    const target=(data.tables||[]).findIndex(t=>t.id===tableId),cards=$$('.rack-card'),card=target>=0?cards[target]:null;
    card?.scrollIntoView({behavior:'smooth',block:'center'});card?.classList.add('go-table-flash');setTimeout(()=>card?.classList.remove('go-table-flash'),1800);
  });
}
function tableMoveAdminPanel(){
  const req=(data.table_move_requests||[]).filter(x=>x.status==='pending');if(role!=='admin')return '';
  return `<section class="card glass v161-admin-panel"><div class="row split"><div><div class="eyebrow">ADMIN APPROVAL</div><h2>Rackmaster Table-Move Requests</h2></div><span class="pill ${req.length?'pending':'good'}">${req.length} PENDING</span></div>${req.length?req.map(r=>`<article class="approval-row">${avatar(r.player||{full_name:'Player'},'md')}<div class="grow"><b>${esc(r.player?.full_name||'Player')}</b><small>${esc(r.from_table_name||'Table')} → ${esc(r.to_table_name||'Table')}</small></div><button class="btn good" onclick="resolveTableMove('${r.id}',true)">Approve</button><button class="btn danger" onclick="resolveTableMove('${r.id}',false)">Decline</button></article>`).join(''):'<div class="empty">No rackmaster table-move requests awaiting approval.</div>'}</section>`;
}
activePlayersView=function(){
  const rows=activePlayers();
  return `${tableMoveAdminPanel()}<section class="hero-panel glass compact-hero v161-active-hero"><div><div class="eyebrow">ACTIVE PLAYER LIST</div><h2>${rows.length} Players In The Turn System</h2><p>Live identification, queue status and table assignment.</p></div><button class="btn danger delete-select-btn" onclick="openDeletePlayerDialog('active')">🗑 Delete Player</button></section>
  <section class="card glass"><div class="active-player-grid">${rows.map(x=>`<article class="active-player-card">${avatar(x.p,'lg')}<div class="grow"><div class="row wrap"><b>${esc(x.p.full_name)}</b><span class="pill ${x.status.includes('PLAYING')?'good':x.status.includes('PAYMENT')?'pending':''}">${esc(x.status)}</span></div><small class="mono-id">${esc(x.p.player_code||'ID pending')}</small><div class="active-meta"><span>🎱 ${esc(x.table_name)}</span>${x.position?`<span>Queue #${x.position}</span>`:''}</div></div><button class="btn go-table-btn" onclick="goToTable('${x.table_id}')">🎱 Go To Table</button><button class="icon-action" title="Update photo" onclick="pickPlayerPhoto('${x.p.id}')">📷</button></article>`).join('')||'<div class="empty">No active players.</div>'}</div></section>`;
};

const v161RegistryBase=registryView;
registryView=function(){const base=v161RegistryBase();if(role!=='admin')return base;return `<section class="card glass registry-delete-toolbar"><div><div class="eyebrow">REGISTRY CONTROL</div><b>Delete a selected player</b></div><button class="btn danger" onclick="openDeletePlayerDialog('registry')">🗑 Delete Player</button></section>${base}`};
function openDeletePlayerDialog(scope='registry'){
  let list=scope==='active'?activePlayers().map(x=>x.p):(data.registry||[]);const seen=new Set();list=list.filter(p=>p?.id&&!seen.has(p.id)&&seen.add(p.id));if(!list.length)return toast('No players are available to delete.');
  openModal(`<div class="modal-head"><div><div class="eyebrow">ADMIN · DELETE PLAYER</div><h2>Select Player</h2></div><button class="icon-btn" onclick="closeModal()">×</button></div><div class="notice danger-note">Deleting removes the player from the active Players Turn registry. Match/payment history is retained. Players currently in a live match or holding a table cannot be deleted.</div><div class="field"><label>PLAYER</label><select id="deletePlayerSelect" class="v161-contrast-select">${list.sort((a,b)=>a.full_name.localeCompare(b.full_name)).map(p=>`<option value="${p.id}">${esc(p.player_code||'')} · ${esc(p.full_name)}</option>`).join('')}</select></div><button class="btn danger block" onclick="confirmDeletePlayer()">Delete Selected Player</button>`);
}
async function confirmDeletePlayer(){const id=$('#deletePlayerSelect')?.value,p=(data.registry||data.players||[]).find(x=>x.id===id)||player(id);if(!id)return;if(!confirm(`Delete ${p.full_name||'this player'} from Players Turn?`))return;try{const j=await v161('delete_player',{player_id:id});closeModal();toast(j.message||'Player deleted');await refresh(false)}catch(e){toast(e.message)}}

staffView=function(){
  if(role!=='admin')return '<div class="empty">Admin only.</div>';
  const roles=data.staff_roles_v12||[],staff=data.staff_v12||[],racks=roles.filter(x=>x.turn_role==='rackmaster').map(r=>({...r,staff:staff.find(s=>s.id===r.staff_id)})),allCash=roles.filter(x=>x.turn_role==='cashier').map(r=>({...r,staff:staff.find(s=>s.id===r.staff_id)}));
  const namedCash=['PROMISE','NONSO'].map(n=>allCash.find(x=>(x.staff?.full_name||'').toUpperCase()===n)).filter(Boolean),cash=[...namedCash,...allCash.filter(x=>!namedCash.includes(x)&&!/(front desk)/i.test(x.staff?.full_name||''))].slice(0,2),sh=data.active_shift;
  const slot=(x,label)=>x?`<div class="staff-slot">${avatar({full_name:x.staff?.full_name,photo_data:x.profile_photo_data},'md')}<div class="grow"><b>${esc(x.staff?.full_name||label)}</b><small>@${esc(x.staff?.username||'')}</small></div><button class="icon-action" onclick="pickStaffPhoto('${x.staff_id}','${x.turn_role}')">📷</button></div>`:`<div class="staff-slot vacant"><div class="avatar md placeholder">+</div><div><b>${label}</b><small>Vacant</small></div></div>`;
  const staffName=id=>staff.find(s=>s.id===id)?.full_name||'Not selected',tableName=id=>(data.cue_tables_v12||[]).find(t=>t.id===id)?.table_name||'Table',shiftTables=sh?.table_assignments||[];
  return `<section class="hero-panel glass compact-hero"><div><div class="eyebrow">STAFF & SHIFT CONTROL</div><h2>4 Rackmasters · 2 Cashiers · 3 Active Per Shift</h2><p>Each shift uses 2 rackmasters covering 2 tables each, plus 1 cashier.</p></div>${sh?`<span class="pill good">${esc(sh.shift_name)} ACTIVE</span>`:'<span class="pill pending">NO ACTIVE SHIFT</span>'}</section>
  <div class="grid two staff-structure"><section class="card glass"><h2>Rackmaster Structure</h2><p class="muted">Four rackmasters are kept on the roster; two are selected per shift.</p><div class="staff-stack">${[0,1,2,3].map(i=>slot(racks[i],`Rackmaster ${i+1}`)).join('')}</div></section><section class="card glass"><h2>Cashier Structure</h2><p class="muted">PROMISE and NONSO are the two operational cashier accounts; one runs each shift.</p><div class="staff-stack">${[0,1].map(i=>slot(cash[i],`Cashier ${i+1}`)).join('')}</div></section></div>
  <div class="grid two"><section class="card glass"><h2>Create Staff Account</h2><form id="createStaffForm" class="stack"><div class="field"><label>FULL NAME</label><input name="full_name" required></div><div class="field"><label>USERNAME</label><input name="username" required></div><div class="field"><label>PASSWORD</label><input name="password" type="password" minlength="6" required></div><div class="field"><label>ROLE</label><select name="turn_role" class="v161-contrast-select"><option value="rackmaster">Rackmaster</option><option value="cashier">Cashier</option></select></div><div class="field"><label>PROFILE PHOTO</label><input name="photo" type="file" accept="image/*" capture="user"></div><button class="btn primary">Create Staff</button></form></section>
  <section class="card glass"><h2>Active Shift</h2>${sh?`<div class="shift-live"><span class="live-dot"></span><div><b>${esc(sh.shift_name)}</b><small>Started ${new Date(sh.started_at).toLocaleString()}</small></div></div><div class="shift-person"><b>Cashier</b><span>${esc(staffName(sh.cashier_staff_id))}</span></div><div class="shift-person"><b>Rackmaster 1</b><span>${esc(staffName(sh.rackmaster_1_staff_id))} · ${shiftTables.filter(x=>x.rackmaster_staff_id===sh.rackmaster_1_staff_id).map(x=>tableName(x.table_id)).join(', ')}</span></div><div class="shift-person"><b>Rackmaster 2</b><span>${esc(staffName(sh.rackmaster_2_staff_id))} · ${shiftTables.filter(x=>x.rackmaster_staff_id===sh.rackmaster_2_staff_id).map(x=>tableName(x.table_id)).join(', ')}</span></div><button class="btn danger block" onclick="endShift()">End Current Shift</button>`:'<div class="empty">No staff shift is currently active.</div>'}</section></div>
  <section class="card glass section"><h2>Start / Change Shift</h2><form id="shiftForm" class="stack"><div class="form-grid"><div class="field"><label>SHIFT NAME</label><input name="shift_name" placeholder="Morning Shift / Evening Shift" required></div><div class="field"><label>CASHIER ON SHIFT</label><select class="v161-contrast-select" name="cashier_staff_id" required><option value="">Select cashier</option>${cash.map(x=>`<option value="${x.staff_id}">${esc(x.staff?.full_name||'Cashier')} · @${esc(x.staff?.username||'')}</option>`).join('')}</select></div><div class="field"><label>RACKMASTER 1</label><select class="v161-contrast-select" name="rackmaster_1_staff_id" required><option value="">Select rackmaster</option>${racks.map(x=>`<option value="${x.staff_id}">${esc(x.staff?.full_name||'Rackmaster')}</option>`).join('')}</select></div><div class="field"><label>RACKMASTER 2</label><select class="v161-contrast-select" name="rackmaster_2_staff_id" required><option value="">Select rackmaster</option>${racks.map(x=>`<option value="${x.staff_id}">${esc(x.staff?.full_name||'Rackmaster')}</option>`).join('')}</select></div></div><div class="grid two"><div class="field"><label>RACKMASTER 1 · SELECT 2 TABLES</label><div class="check-grid">${(data.cue_tables_v12||[]).map(t=>`<label><input type="checkbox" name="rm1_tables" value="${t.id}"> ${esc(t.table_name)}</label>`).join('')}</div></div><div class="field"><label>RACKMASTER 2 · SELECT 2 TABLES</label><div class="check-grid">${(data.cue_tables_v12||[]).map(t=>`<label><input type="checkbox" name="rm2_tables" value="${t.id}"> ${esc(t.table_name)}</label>`).join('')}</div></div></div><button class="btn primary block">Activate Shift</button></form></section>`;
};

queueRow=function(q,i,tableId){
  const p=player(q.player_id),pendingVertical=(data.move_requests||[]).some(r=>r.status==='pending'&&(r.requester_queue_id===q.id||r.target_queue_id===q.id)),pendingTable=(data.table_move_requests||[]).some(r=>r.status==='pending'&&r.queue_entry_id===q.id),pendingTransfer=(data.player_transfer_requests||[]).some(r=>r.status==='pending'&&r.queue_entry_id===q.id);
  return `<div class="queue-row ${pendingVertical||pendingTable||pendingTransfer?'pending-move':''}"><div class="queue-num">${i+1}</div>${avatar(p,'sm')}<div class="grow"><b>${esc(p.full_name)}</b><small>${payBadge(q)} ${pendingVertical?'<span class="pill pending">ORDER MOVE PENDING</span>':''}${pendingTable?'<span class="pill pending">TABLE MOVE PENDING</span>':''}${pendingTransfer?'<span class="pill pending">PLAYER TRANSFER PENDING</span>':''}</small></div><div class="queue-actions"><button class="icon-action" title="Upload photo" onclick="pickPlayerPhoto('${p.id}')">📷</button><button class="icon-action" title="Move up" onclick="requestMove('${q.id}','up')">↑</button><button class="icon-action" title="Move down" onclick="requestMove('${q.id}','down')">↓</button><button class="btn small move-table-btn" ${pendingTable?'disabled':''} onclick="openTableMoveRequest('${q.id}','${tableId}')">⇄ Table</button><button class="btn small call-btn" onclick="callPlayer('${q.id}')">🔔 Call</button><button class="btn small danger leave-arena-btn" onclick="staffLeaveArena('${q.id}','${esc(p.full_name).replaceAll("'","&#39;")}')">🚪 Leave Arena</button></div></div>`;
};

rackTable=function(t){
  const st=state(t.id),m=currentMatch(t.id),q=waiting(t.id);
  return `<section class="card glass rack-card"><div class="table-head"><div><div class="eyebrow">${esc(st.activity_status.replaceAll('_',' '))}</div><h2>${esc(t.table_name)}</h2></div><span class="status-light ${st.operational_status}">${st.operational_status}</span></div>
  ${holderDisplay(t.id)}${breakPair(t.id)}
  ${m?`<div class="match-box"><span>LIVE MATCH ${m.match_mode!=='normal'?`· ${esc(m.match_mode.replaceAll('_',' '))}`:''}</span><div class="versus">${avatar(player(m.holder_player_id),'md')}<b>${esc(player(m.holder_player_id).full_name)}</b><strong>VS</strong>${avatar(player(m.challenger_player_id),'md')}<b>${esc(player(m.challenger_player_id).full_name)}</b></div><button class="btn primary block" onclick="openFinishMatch('${m.id}')">Finish Match / Record Result</button></div>`:`<button class="btn primary block" onclick="startNext('${t.id}')">▶ Start Next Match</button>`}
  <div class="queue-list"><div class="queue-title"><b>QUEUE</b><span>${q.length} waiting · ~${waitMin(t.id)} min</span></div>${q.length?q.map((x,i)=>queueRow(x,i,t.id)).join(''):'<div class="empty">No players waiting.</div>'}</div>
  <div class="row wrap table-tools"><button class="btn small" onclick="setTableStatus('${t.id}','open')">Open</button><button class="btn small" onclick="setTableStatus('${t.id}','paused')">Pause</button><button class="btn small danger" onclick="resetTable('${t.id}')">↺ Request Reset</button></div></section>`;
};

function v161ApprovalPanel(){
  const ci=(data.checkin_requests||[]).filter(x=>x.status==='pending'),tr=(data.player_transfer_requests||[]).filter(x=>x.status==='pending'),rr=(data.reset_requests||[]).filter(x=>x.status==='pending');if(!(role==='admin'||role==='rackmaster'))return '';const actorId=data.actor?.staff_id||null;
  const checkins=ci.length?`<section class="card glass approval-panel"><div class="row split"><div><div class="eyebrow">QUEUE ENTRY APPROVAL</div><h2>Cashier Check-ins</h2></div><span class="pill pending">${ci.length} PENDING</span></div>${ci.map(r=>{const p=player(r.player_id),t=maps().t[r.table_id];return `<article class="approval-row">${avatar(p,'md')}<div class="grow"><b>${esc(p.full_name)}</b><small>${esc(t?.table_name||'Table')} · ${money(r.amount)} · ${esc(r.source.toUpperCase())}</small></div><button class="btn good" onclick="resolveCheckin161('${r.id}',true)">✓ Approve</button><button class="btn danger" onclick="resolveCheckin161('${r.id}',false)">Decline</button></article>`}).join('')}</section>`:'';
  const transfers=tr.length?`<section class="card glass approval-panel"><div class="row split"><div><div class="eyebrow">PLAYER TABLE TRANSFER</div><h2>Exit / Entry Approvals</h2></div><span class="pill pending">${tr.length} PENDING</span></div>${tr.map(r=>{const p=player(r.player_id),from=maps().t[r.from_table_id],to=maps().t[r.to_table_id],srcMine=r.source_rackmaster_staff_id===actorId,tgtMine=r.target_rackmaster_staff_id===actorId,roleText=srcMine&&tgtMine?'EXIT + ENTRY APPROVAL':srcMine?'EXIT APPROVAL':tgtMine?'ENTRY APPROVAL':'MONITOR';return `<article class="approval-row">${avatar(p,'md')}<div class="grow"><b>${esc(p.full_name)}</b><small>${esc(from?.table_name||'Table')} → ${esc(to?.table_name||'Table')}</small><div class="approval-state"><span>${esc(roleText)}</span><span>Exit: ${esc(r.source_approval)}</span><span>Entry: ${esc(r.target_approval)}</span></div></div>${role==='rackmaster'&&(srcMine||tgtMine)?`<button class="btn good" onclick="resolveTransfer161('${r.id}',true)">✓ Approve</button><button class="btn danger" onclick="resolveTransfer161('${r.id}',false)">Decline</button>`:''}</article>`}).join('')}</section>`:'';
  const resets=rr.length?`<section class="card glass approval-panel"><div class="row split"><div><div class="eyebrow">TABLE RESET</div><h2>Admin Confirmation</h2></div><span class="pill pending">${rr.length} PENDING</span></div>${rr.map(r=>`<article class="approval-row"><div class="grow"><b>${esc(maps().t[r.table_id]?.table_name||'Table')}</b><small>Reset requested · current holder will be moved to first in queue</small></div>${role==='admin'?`<button class="btn good" onclick="resolveReset161('${r.id}',true)">✓ Confirm Reset</button><button class="btn danger" onclick="resolveReset161('${r.id}',false)">Decline</button>`:'<span class="pill pending">WAITING FOR ADMIN</span>'}</article>`).join('')}</section>`:'';
  return checkins+transfers+resets;
}
rackmasterView=function(){const visible=data.tables||[],others=(data.all_table_summaries||[]).filter(x=>!visible.some(t=>t.id===x.id));return `${role==='rackmaster'?`<section class="card glass section"><div class="eyebrow">MY TABLES</div><h2>${visible.length} table${visible.length===1?'':'s'} assigned</h2><p class="muted">Your current shift assignment controls approvals, resets and player transfers.</p>${others.length?`<div class="row wrap">${others.map(x=>`<button class="btn small" onclick="requestTableAccess('${x.id}')">Request ${esc(x.table_name)}</button>`).join('')}</div>`:''}</section>`:''}${v161ApprovalPanel()}<div class="grid rack-grid">${visible.map(t=>rackTable(t)).join('')}</div>`};
async function resolveCheckin161(id,approve){try{const j=await v161('resolve_checkin',{request_id:id,approve});toast(j.message||'Check-in updated');await refresh(false)}catch(e){toast(e.message)}}
async function resolveTransfer161(id,approve){try{const j=await v161('resolve_transfer',{request_id:id,approve});toast(j.message||'Transfer updated');await refresh(false)}catch(e){toast(e.message)}}
async function staffLeaveArena(id,name){if(!confirm(`${name||'Player'} will leave the arena and be removed from this queue. Continue?`))return;try{const j=await v161('leave_queue_staff',{queue_id:id});toast(j.message||'Player left arena');await refresh(false)}catch(e){toast(e.message)}}
async function resetTable(id){if(!confirm('Send a table reset request to Admin? The current table holder will become first in queue if the reset is approved.'))return;try{const j=await v161('request_reset',{table_id:id});toast(j.message);await refresh(false)}catch(e){toast(e.message)}}
async function resolveReset161(id,approve){try{const j=await v161('resolve_reset',{request_id:id,approve});toast(j.message||'Reset request updated');await refresh(false)}catch(e){toast(e.message)}}

function v161MemberPreview(m){return `<div class="member-verify-card ${m.membership_status==='ACTIVE'?'verified':'not-active'}">${m.photo_data?`<img class="member-verify-photo" src="${m.photo_data}" alt="">`:`<div class="member-verify-photo placeholder">${esc((m.full_name||'?').slice(0,1))}</div>`}<div class="grow"><div class="eyebrow">MEMBER ID · ${esc(m.member_code||'')}</div><h3>${esc(m.full_name||'Member')}</h3><div class="member-verify-meta"><span>${esc(m.current_plan_name||'No active plan')}</span><span>${esc(m.membership_status)}</span><span>Expires ${esc(m.expiry_date||'—')}</span></div></div></div>`}
function wireCashier161(){
  const rf=$('#registeredQueueForm');if(rf){const fresh=rf.cloneNode(true);rf.replaceWith(fresh);fresh.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(fresh);try{const j=await v161('request_registered_checkin',{player_id:f.get('player_id'),table_id:f.get('table_id'),amount:f.get('amount'),reference:f.get('reference')});toast(j.message);await refresh(false)}catch(x){toast(x.message)}});showSelectedPlayer()}
  const wf=$('#walkinForm');if(wf){const fresh=wf.cloneNode(true);wf.replaceWith(fresh);fresh.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(fresh);try{const file=f.get('photo'),photo=file&&file.size?await compressImage(file):'';const j=await v161('request_walkin_checkin',{full_name:f.get('full_name'),phone:f.get('phone'),table_id:f.get('table_id'),amount:f.get('amount'),reference:f.get('reference'),photo_data:photo});toast(j.message);fresh.reset();await refresh(false)}catch(x){toast(x.message)}})}
  const mf=$('#memberQueueForm');if(mf){const label=mf.querySelector('label');if(label)label.textContent='MEMBER ID';const inp=mf.querySelector('#cardToken');if(inp){inp.name='member_id';inp.placeholder='e.g. D12-2026-648647'}mf.querySelectorAll('button,a').forEach(el=>{const txt=(el.textContent||'').toLowerCase();if(txt.includes('camera')||txt==='paste'||txt==='image'||txt.includes('google play')||txt.includes('app store')||el.id==='verifyMembershipBtn')el.remove()});const section=mf.closest('section');section?.querySelectorAll('p.muted').forEach(p=>{if(/external scanner/i.test(p.textContent||''))p.remove()});let preview=mf.querySelector('#membershipPreview');if(!preview){preview=document.createElement('div');preview.id='membershipPreview';preview.className='membership-preview';const table=mf.querySelector('select[name="table_id"]')?.closest('.field');table?.before(preview)}if(preview)preview.innerHTML='<div class="empty">Enter the Member ID from the D12 Membership Registry.</div>';const submit=[...mf.querySelectorAll('button')].find(b=>b.type==='submit'||!b.type);if(submit)submit.textContent='Verify Member ID & Add';const fresh=mf.cloneNode(true);mf.replaceWith(fresh);fresh.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(fresh);try{const lookup=await v161('membership_lookup',{member_id:f.get('member_id')}),m=lookup.member,host=fresh.querySelector('#membershipPreview');if(host)host.innerHTML=v161MemberPreview(m);if(m.membership_status!=='ACTIVE')throw new Error('Membership is expired. Renew the subscription or use daily payment.');const j=await turn('enqueue_member',{card_token:m.card_token,table_id:f.get('table_id')});toast(`${m.full_name} · ${m.member_code} checked in`);showTicket(j.ticket);await refresh(true)}catch(x){toast(x.message);const host=fresh.querySelector('#membershipPreview');if(host&&!host.querySelector('.member-verify-card'))host.innerHTML=`<div class="notice danger-note">${esc(x.message)}</div>`}})}
}
const v161BindFormsBase=bindForms;bindForms=function(){v161BindFormsBase();wireCashier161()};

function transferStatusCard(r,d){const from=d.table?.table_name||'Current table',to=(d.other_tables_summary||[]).find(x=>x.id===r.to_table_id)?.table_name||'New table';return `<section class="card glass transfer-status-card"><div class="eyebrow">TABLE MOVE REQUEST</div><h3>${esc(from)} → ${esc(to)}</h3><div class="approval-state"><span>EXIT RACKMASTER: ${esc(r.source_approval.toUpperCase())}</span><span>ENTRY RACKMASTER: ${esc(r.target_approval.toUpperCase())}</span></div><p class="muted">${r.status==='pending'?'You remain in your current queue until both Rackmasters approve.':'Transfer '+r.status+'.'}</p></section>`}
renderPlayer=function(d){
  const q=d.queue,requests=d.move_requests||[],transfers=d.transfer_requests||[],pendingTransfer=transfers.find(x=>x.status==='pending'),canMove=['queued','called'].includes(q.status);
  $('#playerBody').innerHTML=`<section class="card glass player-main">${avatar(d.player,'xl')}<div><div class="eyebrow">${d.player.member?'D12 MEMBER':'D12 PLAYER'} · ${esc(d.player.player_code||'')}</div><h2>${esc(d.player.full_name)}</h2><div class="player-status">${esc(q.label)}</div><h3>${esc(d.table.table_name)}</h3>${q.position?`<div class="position-ring"><b>${q.position}</b><span>QUEUE POSITION</span></div><p>You are number <b>${q.position}</b> in the queue. Please stay close and be ready.</p><p class="muted">Estimated wait: ${q.estimated_wait_minutes} min</p>`:''}<div class="player-portal-actions"><button class="btn primary" onclick="enableAlerts()">🔔 Enable Alerts</button>${canMove&&!pendingTransfer?`<button class="btn move-player-btn" onclick="openPlayerTableMoveFromData()">⇄ Move To Table</button>`:''}<button class="btn danger" onclick="playerLeaveArena()">🚪 Leave Arena</button></div></div></section>
  ${pendingTransfer?transferStatusCard(pendingTransfer,d):''}
  ${requests.length?`<section class="card glass"><div class="eyebrow">QUEUE EXCHANGE APPROVAL</div><h3>Another player wants to exchange positions</h3>${requests.map(r=>`<div class="move-request">${r.requester_photo?`<img class="avatar md" src="${r.requester_photo}" alt="">`:`<div class="avatar md placeholder">${esc(r.requester_name.slice(0,1))}</div>`}<div class="grow"><b>${esc(r.requester_name)}</b><small>Approve or decline this queue-order change.</small></div><button class="btn good" onclick="respondMove('${r.id}',true)">Approve</button><button class="btn danger" onclick="respondMove('${r.id}',false)">Decline</button></div>`).join('')}</section>`:''}
  <section class="card glass player-table-summary"><div class="eyebrow">OTHER TABLES</div><h3>Live Table Summary</h3><div class="grid table-summaries">${(d.other_tables_summary||[]).map(x=>`<div class="summary-card"><div class="summary-ring">${x.queue_count}</div><div><b>${esc(x.table_name)}</b><p>${x.queue_count} in line · ${x.estimated_wait_minutes} min wait</p></div></div>`).join('')}</div></section>
  ${(d.notifications||[]).length?`<section class="card glass"><div class="eyebrow">LATEST ALERTS</div>${d.notifications.slice(0,5).map(n=>`<div class="portal-notice"><b>${esc(n.kind.replaceAll('_',' ').toUpperCase())}</b><span>${esc(n.message)}</span></div>`).join('')}</section>`:''}`;
  window.__d12PlayerTableSummaries=d.other_tables_summary||[];
};
function openPlayerTableMoveFromData(){const open=(window.__d12PlayerTableSummaries||[]).filter(x=>x.operational_status==='open');if(!open.length)return toast('No other open table is available.');openModal(`<div class="modal-head"><div><div class="eyebrow">PLAYER TABLE MOVE</div><h2>Select New Table</h2></div><button class="icon-btn" onclick="closeModal()">×</button></div><div class="notice">Your current Rackmaster must approve your exit and the incoming Rackmaster must approve your entry. You stay in your current queue until both approve.</div><form id="playerTransferForm" class="stack"><div class="field"><label>MOVE TO TABLE</label><select name="target_table_id" class="v161-contrast-select">${open.map(x=>`<option value="${x.id}">${esc(x.table_name)} · ${x.queue_count} in line · ~${x.estimated_wait_minutes} min</option>`).join('')}</select></div><button class="btn primary block">Send Move Request</button></form>`);$('#playerTransferForm')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{const j=await ticketApi('request_table_transfer',{ticket:ticketParam,target_table_id:f.get('target_table_id')});closeModal();toast(j.message);await pollPlayer(false)}catch(x){toast(x.message)}})}
async function playerLeaveArena(){if(!confirm('Leave the arena and close your current D12 queue position?'))return;try{const j=await ticketApi('leave_arena',{ticket:ticketParam});toast(j.message);await pollPlayer(false)}catch(x){toast(x.message)}}

const v161SettingsBase=settingsView;settingsView=function(){return v161SettingsBase().replaceAll('Version 1.2','Version 1.6.1').replaceAll('Save Version 1.2 Settings','Save Version 1.6.1 Settings')};
